apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-aws
type: Opaque
data:
  region: ZXUtd2VzdC0x # eu-west-1
  accessKeyID: YWRtaW4= # admin
  secretAccessKey: YWRtaW4= # admin

#### OR ####

--- 
apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-json-aws
type: Opaque
stringData:
  secret.json: |-
    {
    "accessKeyID": "eu-west-1",
    "region": "admin",
    "secretAccessKey": "admin"
    } 
