// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gardener/etcd-backup-restore/pkg/health/membergarbagecollector (interfaces: MGCChecker)

// Package membergarbagecollector is a generated GoMock package.
package membergarbagecollector

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMGCChecker is a mock of MGCChecker interface.
type MockMGCChecker struct {
	ctrl     *gomock.Controller
	recorder *MockMGCCheckerMockRecorder
}

// MockMGCCheckerMockRecorder is the mock recorder for MockMGCChecker.
type MockMGCCheckerMockRecorder struct {
	mock *MockMGCChecker
}

// NewMockMGCChecker creates a new mock instance.
func NewMockMGCChecker(ctrl *gomock.Controller) *MockMGCChecker {
	mock := &MockMGCChecker{ctrl: ctrl}
	mock.recorder = &MockMGCCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMGCChecker) EXPECT() *MockMGCCheckerMockRecorder {
	return m.recorder
}

// RemoveSuperfluousMembers mocks base method.
func (m *MockMGCChecker) RemoveSuperfluousMembers(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSuperfluousMembers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSuperfluousMembers indicates an expected call of RemoveSuperfluousMembers.
func (mr *MockMGCCheckerMockRecorder) RemoveSuperfluousMembers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSuperfluousMembers", reflect.TypeOf((*MockMGCChecker)(nil).RemoveSuperfluousMembers), arg0)
}
