apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-azure
type: Opaque
data: 
  storageAccount: YWRtaW4= # admin
  storageKey: YWRtaW4= # admin
  # storageAPIEndpoint: http[s]://<storage-account>.<domain> # override the ABS endpoint

#### OR ####

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-json-azure
type: Opaque
stringData:
  secret.json: |-
    {
    "storageAccount": "admin",
    "storageKey": "admin"
    } 



