apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-azure
type: Opaque
data: 
  storageAccount: YWRtaW4= # admin
  storageKey: YWRtaW4= # admin
  # emulatorEnabled: dHJ1ZQ== # true (optional)
  # storageAPIEndpoint: aHR0cDovL2F6dXJpdGUtc2VydmljZToxMDAwMA== # http://azurite-service:10000 (optional)
