apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-aws
type: Opaque
data:
  region: ZXUtd2VzdC0x # eu-west-1
  accessKeyID: YWRtaW4= # admin
  secretAccessKey: YWRtaW4= # admin
# endpoint: # used for S3 compatible providers
# s3ForcePathStyle: # set to `true` for S3 compliant providers
# insecureSkipVerify: # set to `true` for S3 private deployments to skip certificate check
# trustedCaCert: # set a trusted Certificate authority for private deployments like minio
