apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-aliCloud
type: Opaque
data:
  accessKeyID: YWRtaW4= # admin
  accessKeySecret: YWRtaW4= # admin
  storageEndpoint: aHR0cHM6Ly9vc3MtcmVnaW9uLmV4YW1wbGUuY29t # https://oss-region.example.com
  
### OR ###

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-json-aliCloud
type: Opaque
stringData:
  secret.json: |-
    {
      "accessKeyID": "admin",
      "accessKeySecret": "admin",
      "storageEndpoint": "https://oss-region.example.com"
    } 

