apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-ocs
type: Opaque
data:
  accessKeyID: YWRtaW4= # admin
  secretAccessKey: YWRtaW4= # admin
  endpoint: aHR0cHM6Ly9vY3Mub3BlbnNoaWZ0Lm9yZw== # https://ocs.openshift.org
  region: cmVnaW9uMQ== #region1

### OR ###

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: example-json-ocs
type: Opaque
stringData:
  secret.json: |-
    {
      "accessKeyID": "admin",
      "secretAccessKey": "admin",
      "endpoint": "https://ocs.openshift.org",
      "region": "region1"
    }

