#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

# For all steps, concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.
# BINARY_PATH - path to an existing (empty) directory to place build results into.
if [[ -z "${SOURCE_PATH}" ]]; then
  SOURCE_PATH="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
else
  SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi
export SOURCE_PATH

source "${SOURCE_PATH}/.ci/common.sh"

if [[ -z "${BINARY_PATH}" ]]; then
  export BINARY_DIR="${SOURCE_PATH}/bin"
else
  export BINARY_DIR="$(readlink -f "${BINARY_PATH}")/bin"
fi

###############################################################################

cd "${SOURCE_PATH}"

echo "> Building etcd-backup-restore."
BINARY_DIR="${BINARY_DIR}" \
make build
echo "> Finished build."