#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0
set -o errexit
set -o nounset
set -o pipefail

export SOURCE_PATH="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
source "${SOURCE_PATH}/.ci/common.sh"

###############################################################################

cd "${SOURCE_PATH}"

echo "> Running check..."
make check

# Run Static Application Security Testing (SAST) using gosec
echo "> Running SAST checks..."
make sast-report

echo -e "\nAll checks successful"
