#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
set -o errexit
set -o pipefail

# For all steps, concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.
if [[ -z "${SOURCE_PATH}" ]]; then
  SOURCE_PATH="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
else
  SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi
export SOURCE_PATH

source "${SOURCE_PATH}/.ci/common.sh"

export BINARY_DIR="${SOURCE_PATH}/bin"

# AWS_PAGER set to empty string to fix "Unable to redirect output to pager" error
# https://stackoverflow.com/questions/57953187/aws-cli-has-no-output/68361849#68361849
export AWS_PAGER=""

if [ "$USE_CC_SERVER_CACHE" == true ] ; then
  export CC_CACHE_FILE_FLAG="--cache-file dev/server.cache"
fi

###############################################################################

cd "${SOURCE_PATH}"

echo "> Running integration tests."
BINARY_DIR="${BINARY_DIR}" \
AWS_PAGER="${AWS_PAGER}" \
USE_CC_SERVER_CACHE="${USE_CC_SERVER_CACHE}" \
make test-integration
echo "> Finished executing integration tests."
