#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
set -e

# For the test step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
else
  READLINK_BIN="readlink"
fi

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(${READLINK_BIN} -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(${READLINK_BIN} -f "${SOURCE_PATH}")"
fi

echo "SOURCEPATH=$SOURCE_PATH"

##############################################################################

echo "Starting performance regression tests."

set +e

if [ "$PERF_TEST_KUBECONFIG" == "" ]; then
  PERF_TEST_KUBECONFIG=$TM_KUBECONFIG_PATH/shoot.config
fi

ETCD_VERSION=${ETCD_VERSION:-"v3.4.13-bootstrap-1"}
if [ "$ETCD_VERSION" != "" ]; then
  ETCD_IMAGE=${ETCD_IMAGE:-"europe-docker.pkg.dev/gardener-project/public/gardener/etcd:$ETCD_VERSION"}
fi

if [ "$ETCDBR_VERSION" != "" ]; then
  ETCDBR_IMAGE=${ETCDBR_IMAGE:-"europe-docker.pkg.dev/gardener-project/public/gardener/etcdbrctl:$ETCDBR_VERSION"}
fi

if [ -r "$PERF_TEST_KUBECONFIG" ]; then
  ETCD_IMAGE=$ETCD_IMAGE ETCDBR_IMAGE=$ETCDBR_IMAGE KUBECONFIG=$PERF_TEST_KUBECONFIG ginkgo -v test/perf/regression
  TEST_RESULT=$?
else
  echo "Invalid kubeconfig for performance tests $PERF_TEST_KUBECONFIG"
  TEST_RESULT=255
fi

set -e

echo "Done with performance regression tests."

exit $TEST_RESULT
