#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

export SOURCE_PATH="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
source "${SOURCE_PATH}/.ci/common.sh"

###############################################################################

cd "${SOURCE_PATH}"

echo "> Running unit tests."
make test-unit
echo "> Finished executing unit tests."
