#!/bin/bash -eu
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# install python requirements if needed
if ! pip list 2>&1 | grep Mako &>/dev/null; then
  pip install Mako
fi

CONTAINER=${1:-etcd-store}
PATH_TEMPLATES="$(dirname $0)/templates"
PATH_EXAMPLES="$(dirname $0)/../example"

mkdir -p "$PATH_EXAMPLES"

# render cloud-specific templates
for cloud in aws azure gcp openstack local; do
  echo "* Rendering manifests for cloud '$cloud':"
  for resource in etcd-statefulset; do
    echo "  * Template '$resource' rendered."
    mako-render --var cloud="$cloud" --var container="$CONTAINER" "$PATH_TEMPLATES/$resource.yaml.tpl" > "$PATH_EXAMPLES/$resource-$cloud.yaml"
  done
  echo
done