{{- if .Values.backupRestoreTLS }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-etcdbr-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  bundle.crt: {{ .Values.backupRestoreTLS.caBundle | b64enc }}
{{- end }}