{{- if .Values.tls.etcdBackupRestore }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-etcdbr-client-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.etcdBackupRestore.client.crt | b64enc }}
  tls.key: {{ .Values.tls.etcdBackupRestore.client.key | b64enc }}
{{- end }}
