{{- if gt (int .Values.replicas) 1 }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name}}-etcd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
